Search.appendIndex(
    [
                {
            "fqsen": "\\Zeantar\\Docblock\\Docblock",
            "name": "Docblock",
            "summary": "Docblock\u0020class",
            "url": "classes/Zeantar-Docblock-Docblock.html"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\Docblock\u003A\u003AappendStrings\u0028\u0029",
            "name": "appendStrings",
            "summary": "Assigns\u0020line\u0020as\u0020summary\u0020or\u0020adds\u0020to\u0020description",
            "url": "classes/Zeantar-Docblock-Docblock.html#method_appendStrings"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\Docblock\u003A\u003ApopulateTags\u0028\u0029",
            "name": "populateTags",
            "summary": "Populates\u0020tags\u0020dictionary\nAssigns\u0020reference\u0020to\u0020tag\u0020as\u0020value\u0020and\u0020tag\u0020name\u0020as\u0020key",
            "url": "classes/Zeantar-Docblock-Docblock.html#method_populateTags"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\Docblock\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Zeantar-Docblock-Docblock.html#method___construct"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\Docblock\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Returns\u0020raw\u0020docblock",
            "url": "classes/Zeantar-Docblock-Docblock.html#method___toString"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\Docblock\u003A\u003AgetSummary\u0028\u0029",
            "name": "getSummary",
            "summary": "Returns\u0020summary\u0020of\u0020docblock",
            "url": "classes/Zeantar-Docblock-Docblock.html#method_getSummary"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\Docblock\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "Returns\u0020description\u0020of\u0020docblock",
            "url": "classes/Zeantar-Docblock-Docblock.html#method_getDescription"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\Docblock\u003A\u003AgetLine\u0028\u0029",
            "name": "getLine",
            "summary": "Returns\u0020line\u0020at\u0020index",
            "url": "classes/Zeantar-Docblock-Docblock.html#method_getLine"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\Docblock\u003A\u003AgetLines\u0028\u0029",
            "name": "getLines",
            "summary": "Returns\u0020array\u0020of\u0020docblock\u0020lines",
            "url": "classes/Zeantar-Docblock-Docblock.html#method_getLines"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\Docblock\u003A\u003AgetTag\u0028\u0029",
            "name": "getTag",
            "summary": "Returns\u0020docblock\u0020tag\u0020by\u0020name",
            "url": "classes/Zeantar-Docblock-Docblock.html#method_getTag"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\Docblock\u003A\u003AfromReflection\u0028\u0029",
            "name": "fromReflection",
            "summary": "Returns\u0020new\u0020docblock\u0020object\u0020from\u0020reflection",
            "url": "classes/Zeantar-Docblock-Docblock.html#method_fromReflection"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\Docblock\u003A\u003AfromClass\u0028\u0029",
            "name": "fromClass",
            "summary": "Returns\u0020new\u0020docblock\u0020object\u0020from\u0020class",
            "url": "classes/Zeantar-Docblock-Docblock.html#method_fromClass"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\Docblock\u003A\u003AfromMethod\u0028\u0029",
            "name": "fromMethod",
            "summary": "Returns\u0020new\u0020docblock\u0020object\u0020from\u0020class\u0020method",
            "url": "classes/Zeantar-Docblock-Docblock.html#method_fromMethod"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\Docblock\u003A\u003AfromProperty\u0028\u0029",
            "name": "fromProperty",
            "summary": "Returns\u0020new\u0020docblock\u0020object\u0020from\u0020class\u0020property",
            "url": "classes/Zeantar-Docblock-Docblock.html#method_fromProperty"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\Docblock\u003A\u003A\u0024lines",
            "name": "lines",
            "summary": "Lines\u0020of\u0020docblock",
            "url": "classes/Zeantar-Docblock-Docblock.html#property_lines"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\Docblock\u003A\u003A\u0024tagDictionary",
            "name": "tagDictionary",
            "summary": "Dictionary\u0020of\u0020tags",
            "url": "classes/Zeantar-Docblock-Docblock.html#property_tagDictionary"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\Docblock\u003A\u003A\u0024summary",
            "name": "summary",
            "summary": "Docblock\u0020summary",
            "url": "classes/Zeantar-Docblock-Docblock.html#property_summary"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\Docblock\u003A\u003A\u0024description",
            "name": "description",
            "summary": "Docblock\u0020description",
            "url": "classes/Zeantar-Docblock-Docblock.html#property_description"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockLine",
            "name": "DocblockLine",
            "summary": "Docblock\u0020line\u0020class",
            "url": "classes/Zeantar-Docblock-DocblockLine.html"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockLine\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Zeantar-Docblock-DocblockLine.html#method___construct"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockLine\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Returns\u0020raw\u0020line",
            "url": "classes/Zeantar-Docblock-DocblockLine.html#method___toString"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockLine\u003A\u003AgetRaw\u0028\u0029",
            "name": "getRaw",
            "summary": "Returns\u0020raw\u0020line",
            "url": "classes/Zeantar-Docblock-DocblockLine.html#method_getRaw"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockLine\u003A\u003AgetContent\u0028\u0029",
            "name": "getContent",
            "summary": "Returns\u0020content\u0020of\u0020docblock\u0020line",
            "url": "classes/Zeantar-Docblock-DocblockLine.html#method_getContent"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockLine\u003A\u003AgetTag\u0028\u0029",
            "name": "getTag",
            "summary": "Returns\u0020tag\u0020on\u0020line\u0020or\u0020null\u0020if\u0020not\u0020present",
            "url": "classes/Zeantar-Docblock-DocblockLine.html#method_getTag"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockLine\u003A\u003AhasTag\u0028\u0029",
            "name": "hasTag",
            "summary": "Returns\u0020if\u0020line\u0020has\u0020a\u0020tag",
            "url": "classes/Zeantar-Docblock-DocblockLine.html#method_hasTag"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockLine\u003A\u003AisEmpty\u0028\u0029",
            "name": "isEmpty",
            "summary": "Returns\u0020if\u0020line\u0020is\u0020empty\u0020\u0028has\u0020no\u0020content\u0029",
            "url": "classes/Zeantar-Docblock-DocblockLine.html#method_isEmpty"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockLine\u003A\u003AisText\u0028\u0029",
            "name": "isText",
            "summary": "Returns\u0020if\u0020line\u0020is\u0020a\u0020text\u0020\u0028not\u0020a\u0020tag\u0020and\u0020not\u0020empty\u0029",
            "url": "classes/Zeantar-Docblock-DocblockLine.html#method_isText"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockLine\u003A\u003AisClosure\u0028\u0029",
            "name": "isClosure",
            "summary": "Returns\u0020if\u0020line\u0020is\u0020a\u0020closure\u0020\u0028\u002A\\\u0020or\u0020\/\u002A\u002A\u0029",
            "url": "classes/Zeantar-Docblock-DocblockLine.html#method_isClosure"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockLine\u003A\u003AfromString\u0028\u0029",
            "name": "fromString",
            "summary": "Creates\u0020and\u0020returns\u0020new\u0020docblock\u0020line\u0020object\u0020from\u0020raw\u0020line",
            "url": "classes/Zeantar-Docblock-DocblockLine.html#method_fromString"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockLine\u003A\u003A\u0024rawString",
            "name": "rawString",
            "summary": "Raw\u0020\u0028unprocessed\u0029\u0020docblock\u0020line",
            "url": "classes/Zeantar-Docblock-DocblockLine.html#property_rawString"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockLine\u003A\u003A\u0024content",
            "name": "content",
            "summary": "Content\u0020of\u0020docblock\u0020line\u0020\u0028ignores\u0020markup\u0029",
            "url": "classes/Zeantar-Docblock-DocblockLine.html#property_content"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockLine\u003A\u003A\u0024tag",
            "name": "tag",
            "summary": "Tag\u0020on\u0020line",
            "url": "classes/Zeantar-Docblock-DocblockLine.html#property_tag"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockTag",
            "name": "DocblockTag",
            "summary": "Docblock\u0020tag\u0020class",
            "url": "classes/Zeantar-Docblock-DocblockTag.html"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockTag\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Zeantar-Docblock-DocblockTag.html#method___construct"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockTag\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "Returns\u0020name\u0020of\u0020tag",
            "url": "classes/Zeantar-Docblock-DocblockTag.html#method_getName"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockTag\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "Returns\u0020value\u0020of\u0020tag\u0020or\u0020null\u0020if\u0020not\u0020present",
            "url": "classes/Zeantar-Docblock-DocblockTag.html#method_getValue"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockTag\u003A\u003AfromLine\u0028\u0029",
            "name": "fromLine",
            "summary": "Returns\u0020new\u0020tag\u0020object\u0020from\u0020line",
            "url": "classes/Zeantar-Docblock-DocblockTag.html#method_fromLine"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockTag\u003A\u003AfromContent\u0028\u0029",
            "name": "fromContent",
            "summary": "Parses\u0020and\u0020returns\u0020new\u0020tag\u0020object\u0020from\u0020raw\u0020line",
            "url": "classes/Zeantar-Docblock-DocblockTag.html#method_fromContent"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockTag\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Zeantar-Docblock-DocblockTag.html#property_name"
        },                {
            "fqsen": "\\Zeantar\\Docblock\\DocblockTag\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/Zeantar-Docblock-DocblockTag.html#property_value"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Zeantar\\Docblock",
            "name": "Docblock",
            "summary": "",
            "url": "namespaces/zeantar-docblock.html"
        },                {
            "fqsen": "\\Zeantar",
            "name": "Zeantar",
            "summary": "",
            "url": "namespaces/zeantar.html"
        }            ]
);
