name: PHPUnit CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@run-as-current-user

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          command: update
      
      - name: Run tests
        uses: php-actions/composer@v6
        with:
          command: test